# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Turn and ToolCall models for agentic workload benchmarking.

These models represent the normalized turn record as specified in the
Agentic Workload Benchmarking Specification. They capture the essential
characteristics of LLM calls within agentic sessions.
"""

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class FinishReason(str, Enum):
    """Reasons for turn completion."""
    STOP = "stop"
    TOOL_CALLS = "tool_calls"
    LENGTH = "length"
    CONTENT_FILTER = "content_filter"
    UNKNOWN = "unknown"


class ToolCall(BaseModel):
    """Represents a tool/function call made during a turn.

    Attributes:
        name: The name of the tool/function called.
        duration_ms: Wall-clock duration of tool execution in milliseconds.
        result_tokens: Number of tokens added to context from tool result.
        arguments: Optional tool call arguments (serialized as string).
        tool_call_id: Optional ID for matching with tool results.
    """
    name: str = Field(..., description="Name of the tool/function called")
    duration_ms: int = Field(
        default=0,
        ge=0,
        description="Wall-clock duration of tool execution in milliseconds"
    )
    result_tokens: int = Field(
        default=0,
        ge=0,
        description="Number of tokens added to context from tool result"
    )
    arguments: Optional[str] = Field(
        default=None,
        description="Tool call arguments (JSON string)"
    )
    tool_call_id: Optional[str] = Field(
        default=None,
        description="ID for matching with tool results"
    )

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            "name": self.name,
            "duration_ms": self.duration_ms,
            "result_tokens": self.result_tokens,
            "arguments": self.arguments,
            "tool_call_id": self.tool_call_id,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ToolCall":
        """Create ToolCall from dictionary."""
        return cls(**data)


class Turn(BaseModel):
    """Represents a single LLM inference call within an agentic session.

    This is the normalized turn record that captures all performance-relevant
    characteristics of an LLM call, regardless of the source format.

    Attributes:
        session_id: Groups turns into sessions.
        turn_index: 0-based position within the session.
        input_tokens: Total input tokens for this LLM call.
        output_tokens: Tokens generated by the model.
        new_context_tokens: input_tokens[N] - input_tokens[N-1].
        finish_reason: Why the turn ended ("stop" or "tool_calls").
        tool_calls: Zero or more tool calls made in this turn.
        llm_latency_ms: Observed LLM call duration from source trace.
        ttft_ms: Time to first token from source trace (if available).
        timestamp_ms: Original timestamp of the turn (for trace replay).
    """
    session_id: str = Field(..., description="Groups turns into sessions")
    turn_index: int = Field(
        ...,
        ge=0,
        description="0-based position within the session"
    )
    input_tokens: int = Field(
        ...,
        ge=0,
        description="Total input tokens for this LLM call"
    )
    output_tokens: int = Field(
        ...,
        ge=0,
        description="Tokens generated by the model"
    )
    new_context_tokens: int = Field(
        default=0,
        ge=0,
        description="Context growth: input_tokens[N] - input_tokens[N-1]"
    )
    finish_reason: FinishReason = Field(
        default=FinishReason.STOP,
        description="Why the turn ended"
    )
    tool_calls: List[ToolCall] = Field(
        default_factory=list,
        description="Tool calls made in this turn"
    )
    llm_latency_ms: Optional[int] = Field(
        default=None,
        ge=0,
        description="Observed LLM call duration from source trace (ms)"
    )
    ttft_ms: Optional[int] = Field(
        default=None,
        ge=0,
        description="Time to first token from source trace (ms)"
    )
    timestamp_ms: Optional[int] = Field(
        default=None,
        ge=0,
        description="Original timestamp of the turn for trace replay (ms)"
    )

    @property
    def has_tool_calls(self) -> bool:
        """Check if this turn has tool calls."""
        return len(self.tool_calls) > 0

    @property
    def total_tool_duration_ms(self) -> int:
        """Total duration of all tool calls in this turn."""
        return sum(tc.duration_ms for tc in self.tool_calls)

    @property
    def total_tool_result_tokens(self) -> int:
        """Total tokens from all tool results in this turn."""
        return sum(tc.result_tokens for tc in self.tool_calls)

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            "session_id": self.session_id,
            "turn_index": self.turn_index,
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "new_context_tokens": self.new_context_tokens,
            "finish_reason": self.finish_reason.value,
            "tool_calls": [tc.to_dict() for tc in self.tool_calls],
            "llm_latency_ms": self.llm_latency_ms,
            "ttft_ms": self.ttft_ms,
            "timestamp_ms": self.timestamp_ms,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Turn":
        """Create Turn from dictionary."""
        if "finish_reason" in data and isinstance(data["finish_reason"], str):
            data = data.copy()
            data["finish_reason"] = FinishReason(data["finish_reason"])

        if "tool_calls" in data and data["tool_calls"]:
            data = data.copy()
            data["tool_calls"] = [
                ToolCall.from_dict(tc) if isinstance(tc, dict) else tc
                for tc in data["tool_calls"]
            ]

        return cls(**data)

    def to_csv_row(self) -> dict:
        """Convert to CSV row format."""
        return {
            "session_id": self.session_id,
            "turn_index": self.turn_index,
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "finish_reason": self.finish_reason.value,
            "num_tool_calls": len(self.tool_calls),
            "tool_duration_ms": self.total_tool_duration_ms,
            "tool_result_tokens": self.total_tool_result_tokens,
            "llm_latency_ms": self.llm_latency_ms or 0,
        }

    @classmethod
    def from_csv_row(cls, row: dict, session_id: str) -> "Turn":
        """Create Turn from CSV row."""
        num_tool_calls = int(row.get("num_tool_calls", 0))
        tool_calls = []

        if num_tool_calls > 0:
            total_duration = int(row.get("tool_duration_ms", 0))
            total_result_tokens = int(row.get("tool_result_tokens", 0))

            for i in range(num_tool_calls):
                tool_calls.append(ToolCall(
                    name=f"tool_{i}",
                    duration_ms=total_duration // num_tool_calls,
                    result_tokens=total_result_tokens // num_tool_calls,
                ))

        finish_reason_str = row.get("finish_reason", "stop")
        try:
            finish_reason = FinishReason(finish_reason_str)
        except ValueError:
            finish_reason = FinishReason.UNKNOWN

        return cls(
            session_id=session_id,
            turn_index=int(row.get("turn_index", 0)),
            input_tokens=int(row.get("input_tokens", 0)),
            output_tokens=int(row.get("output_tokens", 0)),
            finish_reason=finish_reason,
            tool_calls=tool_calls,
            llm_latency_ms=int(row.get("llm_latency_ms", 0)) or None,
        )
